#!/usr/bin/env ruby -rubygems
require 'msgpack/rpc'
require 'tweetstream'

mgr_host, mgr_port = (ARGV.shift || "").split(':')
user = ARGV.shift
pass = ARGV.shift
if !ARGV.empty? || mgr_port.nil? || pass.nil?
	puts "Usage: #{$0} <manager address:port> <twitter user> <twitter pass>"
	exit 1
end

mgr = MessagePack::RPC::Client.new(mgr_host, mgr_port.to_i)
db_addr = mgr.call(:getDBServer)
nodes = mgr.call(:getNodes)
mgr.close

sp = MessagePack::RPC::SessionPool.new
round_robin = 0

start = Time.now
TweetStream::Client.new(user, pass).sample do |stat|
	host, port = nodes[ (round_robin+=1) % nodes.size ]
	sp.get_session(host, port).call(:indexText, stat[:id], stat[:text])
	puts "#{round_robin}\tindexing on #{host}:#{port}: (id=#{stat[:id]}) #{stat[:text]}"
	if round_robin > 50000
		time = Time.now - start
		puts  "ok. (#{time})"
		exit 0
	end
end

